language: elixir

elixir:
  - 1.2.0
  - 1.2.1
  - 1.2.2
  - 1.2.3
  - 1.2.4
  - 1.2.5
  - 1.2.6
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.3.4

otp_release:
  - 18.0
  - 18.1
  - 18.2
  - 18.3
  - 19.0
  - 19.1
  - 19.2

script: "mix local.rebar --force && mix local.hex --force && mix deps.get && mix test"
